### ISSUE TITLE
Feature:Colored Sign's (Config Settings)

### ISSUE THREAD

**Issue by R4Z0R49** [md-5/Deadbolt#10]
Anyway you can change the color of the protected tag ?

[Private] = Red
playername = black
[Clantag] = Gold
[Tonwy] = some other color

Anyhow cheers

**Comment by md-5** [comment]
Yes you can.
Simply use &Number as a prefix. For example as you have suggested:

&4[private]
R4Z0R49
&6[Clantag]
&1[Town]

Will result in the lines being coloured Red, black, gold, then blue. You can use multiple colours on the same line, but the symbols count towards the 15 charcter limit.

**Comment by R4Z0R49** [comment]
Oh thanks for the quick response is there a way to add them into the config file so everyones is always the same

[private] = always red
[clantag] = always gold

If not whats the chance of getting that added in future version (well thats saying i can get java 7 running)

**Comment by daemitus** [comment]
Some sort of EnforceLocale flag shouldnt be too difficult to throw in.

**Comment by md-5** [comment]
Will add later

**Comment by md-5** [comment]
Done
