### ISSUE TITLE
Use metadata for uuid ?

### ISSUE THREAD

**Issue by Miaourt** [md-5/Deadbolt#100]
I don't know very much how metadata work, but if you can store uuid of the player(s) in the sign with metadata,  think the probem of name changing would be in the past ! 
A payer made a private sign : the sign store his uuid in metadata of this sign
the player interact with the sign : plugin check if the uuid is the same and change the playername on the sign with his new player name, and ofc allow them to interact....
This is simple with word xD

**Comment by md-5** [comment]
Meta is lost on restart.

**Comment by Miaourt** [comment]
Oh, right x')...
