### ISSUE TITLE
Simply check uuid when open of a chest ?

### ISSUE THREAD

**Issue by Miaourt** [md-5/Deadbolt#101]
So, why simply check uuid at each open of the container/door/etc, put in cache for the server session, and that all ? With that, with a "little" server impact, we can support name change ? ^^'

**Comment by md-5** [comment]
Where are you going to store it?

**Comment by Miaourt** [comment]
Not going to store, check everytime, with the name provided on the sign, and cache them

**Comment by md-5** [comment]
That wouldn't solve anything

**Comment by Miaourt** [comment]
Mmmh, hard to explain (i'm not english) but after some reflexion, this look more and more weird in my head, sorry for disturbing :/
