### ISSUE TITLE
Doors post 1.8 update wont lock

### ISSUE THREAD

**Issue by PiLoT-** [md-5/Deadbolt#105]
the new doors from 1.8 dont work only the iron and oak doors from back in the day

using spigot 1.8

**Comment by cindyker** [comment]
I've created a pull request to update deadbolt for the new doors. 
https://github.com/daemitus/Deadbolt/pull/106

**Comment by PiLoT-** [comment]
im not sure what that means. is a pull when you contribute code and offer it then they put it in?

**Comment by md-5** [comment]
Solved, see ci.md-5.net for latest version.

**Comment by PiLoT-** [comment]
Have i told you lately i love you?
