### ISSUE TITLE
Doors post 1.8 update wont lock (update)

### ISSUE THREAD

**Issue by PiLoT-** [md-5/Deadbolt#107]
i tried the build by md_5

right click on doors to protect only works on oak and iron doors

if a protect sign is put above oak or iron door it functions normal
if a protect sign is put above new doots it says "nothing near to protect"

**Comment by cindyker** [comment]
the build didn't compile. the Jenkins needs the new spigot jars added.
Ping me on spigot IRC

**Comment by md-5** [comment]
I fixed the build
