### ISSUE TITLE
New doors cannot be locked from blocks adjacent

### ISSUE THREAD

**Issue by Absentee23** [md-5/Deadbolt#108]
Normally with doors, I'm able to place a private sign above or beside them on the wall and have it protect the door, however with any of the new doors, ONLY signs directly on them will detect the door and protect it. When signs are placed above/beside do not detect it as a valid block to protect. Tested alongside the old wood doors in the exact same setup.

Using deadbolt jenkins build 20, and Spigot 1.8: git-Spigot-9a88a38-2ba7357

**Comment by cindyker** [comment]
I thought that was working, just doesn't put auto signs. But I will check it again.

**Comment by Absentee23** [comment]
Seems to be fixed in [build 21](http://ci.md-5.net/job/Deadbolt/21/), thanks!
