### ISSUE TITLE
Feature:Lockable Fence Gates

### ISSUE THREAD

**Issue by R4Z0R49** [md-5/Deadbolt#11]
Pretty much as the title says any plans to bring this in ?

**Comment by daemitus** [comment]
I was maybe halfway through working in that and adding sign options above/below trapdoors when I had a no notice trip to toronto sprung on me. MD5 is on the job however.

**Comment by md-5** [comment]
As daem said already in. Will finalise. For now use the target folder for bleeding edge builds.
