### ISSUE TITLE
1.3.* Discussion

### ISSUE THREAD

**Issue by R4Z0R49** [md-5/Deadbolt#20]
Hello Guys

I've been getting a few problem with the new 1.3.\* versions first of all the color code seems to work fine but does cause problems for players with longer names. I can see your are trying to find a solution to this but would it not be quicker and better to just remove the color code from players names? line 1, 3, 4 color code but Leave line 2 normal would this not fix the problem or at least allow us to turn color coding off for each line?.

I've also noticed players can now break all signs no matter who owns also old signs with no color tags but have longer player names no longer open for the owner even tho the name is fully seen on line two due to these bugs we have had to go back to 1.1 which works perfect

Towny.

Whats the deal with the signs not liking capital letters. All our towns start with capital letters but sign locks will not accept capital letters they all have to be lower case.
example
Notchville = [Notchville] << Does not work it only works if you lowercase it [notchville]
Atlantis = [atlantis] >> [Atlantis] does not work 

not a massive issue but thought id add it.

Going from 1.1 to 1.3 removing all files before starting gives the above problems. 1.1 works perfect before the update :-(

**Comment by daemitus** [comment]
Blame me for rewriting most of the core junk to get signs on top of trapdoors working easier. Now im playing bugcatcher all over again

**Comment by daemitus** [comment]
If youre still on, whats your server IP? Id like to drop an update on you and test

**Comment by daemitus** [comment]
I would kill for a list.containsIgnoreCase()

**Comment by R4Z0R49** [comment]
server info mc1.minerisisle.com

Most of our guys wont be on till later today depending on the test you need i can make a clone of the server and test stuff without any real issue.

**Comment by md-5** [comment]
Daem are you working with this because you screwed them up in the first place. I really cant be bothered but will take look if needs be.

**Comment by daemitus** [comment]
Im pretty sure ive got the towny issue locked in. I wasnt changing to lower before adding to authorized

**Comment by md-5** [comment]
I just read your devbukkit stuff for the first time in a while. all good i suppose

**Comment by daemitus** [comment]
We've got a good one here.
Make a signpost, works as intended.
Make a wallsign (above/below door for example) it truncs to 13 instead of 15.

they both are in the same logic. i have output to the server saying what the sign finalizes as after sign.update. but yet theyre different.

**Comment by daemitus** [comment]
So wall signs are a display issue, the data is all there. Pinned down the isOwner issue with long names finally with this.

**Comment by md-5** [comment]
Sounds like the colour sign bug we had before

**Comment by daemitus** [comment]
signUpdateEvent.getLines[] references back to the event. No need to do setLine afterwards.

Previously, I was updating the sign, but anything I did would be overwrote when the event finished.

**Comment by daemitus** [comment]
Everytime i fix something, I break something else.

**Comment by md-5** [comment]
Its all good. Right?

**Comment by R4Z0R49** [comment]
atm the only bug i've found was the [everyone] tag no longer works this maybe down to towny

**Comment by daemitus** [comment]
[Everyone] fixed 1.3.9

**Comment by R4Z0R49** [comment]
but the question is what did you break :-0 lol

Ill test tomorrow

**Comment by daemitus** [comment]
Didnt change deadbolt.admin.\* to reflect deadbolt.admin.signs->deadbolt.admin.commands
Now it is.
