### ISSUE TITLE
Deadbolt fix does 1/2 a door.

### ISSUE THREAD

**Issue by Inscrutable** [md-5/Deadbolt#21]
Hi Guys. I just tried out 1.3.10, and tested the new fix feature.
Turns out that on doors it only does the half you aim at.

Also had weird issues with wooden doors since 1.3.4.
Iron doors work fine, single or double, with or without timer.
But wooden ones keep immediately slamming in my face, and the one I use becomes misaligned
(The rest of the row of doors works normally). MC1.8.1, CB1185, Java7, Win7...  is it just me?

**Comment by daemitus** [comment]
Fix is designed like that in the rare likelyhood that only half is triggered. Just use it twice. Whats your server ip, id like to see the wood issue.

**Comment by md-5** [comment]
With all these bugs and rewrites it should just be 2.0

**Comment by Inscrutable** [comment]
Server IP yggdrasyl.dyndns.org:25565. I added daemitus, hope that's yer MC name (already added md_5). 
Whitelisted, not up 24/7 but I try. Up for hext 2-3 hrs anyway. Most welcome, senors.
