### ISSUE TITLE
Sign test update

### ISSUE THREAD

**Issue by godsyn** [md-5/Deadbolt#23]
This server is running Craftbukkit version git-Bukkit-1.8.1-R4-13-g342948e-b1488jnks (MC: 1.0.0)
 Deadbolt 1.3.14
When editing a sign (select sign, /db [line] [text]) the sign text doesn't update until you re-log.

**Comment by md-5** [comment]
Not gonna take a look till an rb is out, but I have made note of it.

**Comment by daemitus** [comment]
updated to 1559, still exists. Tried a couple different methods, no luck. Going to let this sit for a couple more Dev builds and see if anything comes up.

**Comment by godsyn** [comment]
http://jd.bukkit.org/doxygen/db/d26/interfaceorg_1_1bukkit_1_1block_1_1Sign.html#a7b2deb5d25e0256a6631de7a51d6377a
Help?
