### ISSUE TITLE
Users with names over 15 Characters

### ISSUE THREAD

**Issue by Toonic** [md-5/Deadbolt#26]
Users with names over 15 Characters are unable to access their chest. Their name gets cut off at the 15th and the plugin deny's access to them.

The only way I could see that could be a possible fix for this is to have the plugin check for the first 15 characters then allow or deny access to the player to the chest, door, or what ever.

**Comment by daemitus** [comment]
At the moment, im trying to truncate names to 13 characters, so even big names can have atleast 1 color, if that option is enabled. Ill fire up griefcraft again and test with a huge name

**Comment by Toonic** [comment]
Thank's for the quick response. I have two users on-line right now complaining about the issue. I'll tell them just to hold off for the time being.

**Comment by daemitus** [comment]
Id suggest downgrading back to the 1.x series and give me an hour or two. Mostly what im doing is efficiency things (and breaking things while i go apparently).

**Comment by Toonic** [comment]
No rush. Both players don't mind waiting.

**Comment by daemitus** [comment]
https://github.com/daemitus/Deadbolt/blob/master/release/2.0.2%201.0.1-R1/Deadbolt.jar?raw=true

**Comment by daemitus** [comment]
Going to add brew stands and enchant tables while I wait for feedback.

**Comment by Toonic** [comment]
When creating a sign now. If I type
[Private]
Cartoonic

it comes out as 
[Private]
CartoonicCart

I don't know if this was recent or not.

**Comment by daemitus** [comment]
Its always something. brb

**Comment by daemitus** [comment]
https://github.com/daemitus/Deadbolt/blob/master/release/2.0.3%201.0.1-R1/Deadbolt.jar?raw=true

**Comment by Toonic** [comment]
That fixxed it. As for the long name issue, they went offline. I'll update you if we have any other problems.

**Comment by daemitus** [comment]
Righto, thanks for the help.

**Comment by daemitus** [comment]
brewing stands, cauldrons, enchantment tables added and quickly tested.
