### ISSUE TITLE
unable to parse manifest details 

### ISSUE THREAD

**Issue by FePython** [md-5/Deadbolt#27]
im using McMyAdmin and when the server start's i get this error with the new build of your plugin 2.0.4

"unable to parse manifest details for './Minecraft/plugins\Deadbolt.jar' "

i downloaded it a few times to see if it might be corrupted but it was not. the plugin runs fine but for whatever reason your new version is not liking McMyAdmin so i thought id let you know

**Comment by daemitus** [comment]
Best guess, something to do with the way maven builds, you want to look at this real quick md5?

**Comment by md-5** [comment]
Ill take a look.
FInally back into the swing of Guardian, getting an irc bot etc

**Comment by md-5** [comment]
Works fine for me. Might wanna update the downloads to use latest build.

**Comment by FePython** [comment]
yeah still going on but only if i run the server with McMyAdmin which is odd im going to say its a bug with MMA not your side maybe there looking for something with your code and not seeing it because other then that your plugin is running fine so at lest its not stopping it from starting. ether way thanks for the quick response
