### ISSUE TITLE
Lockette/Deadbolt bypass

### ISSUE THREAD

**Issue by kylekz** [md-5/Deadbolt#29]
Hacked clients can create an instance of the sign and edit the contents of it, thus bypassing the lock.

**Comment by daemitus** [comment]
Oh thisll be a fun one.

**Comment by md-5** [comment]
I have been doing this
I mean have known about this for ages, yet can't figure out a fix.
I tried to show it to @daemitus but never see him online

**Comment by kylekz** [comment]
Client code is just this:
--SNIP--
To quote Evenprime:
"Each sign has a boolean flag "editable". When you place a sign, it is "true", meaning the next SignUpdate for it will work. Originally after this first update, the flag should become "false", preventing any further edits. But with the MC 1.8 version of CraftBukkit that was no longer the case, it stayed "true" after an edit.

When the sign gets unloaded (server restarting or chunk simply not needed atm) only the text gets stored. When it gets loaded later on, the flag will be initialized to "false". Therefore a sign that has been placed far away from players (such that its chunk can get unloaded at some point) or that has been placed before a server restart is really not editable."

**Comment by md-5** [comment]
As I said, I have known about this for ages, yet don't know a fix.
/me thinks about reflection

**Comment by Evenprime** [comment]
I guess a temporary fix for this on the Lockette side of things would be to listen to the SignChangeEvent and cancel the event if the sign already contains text that is relevant to Lockette (e.g. [private] on the first line).

I also opened a bug report with bukkit (private, hence not visible) explaining the problem in detail and what has to be changed to prevent this.

**Comment by md-5** [comment]
We already do that, not sure about Lockette
I have known about this for ages, yet haven't had a fix.

**Comment by md-5** [comment]
leemme get this, testing now

**Comment by md-5** [comment]
Fixed
