### ISSUE TITLE
Door timers: need to recognize premature closure

### ISSUE THREAD

**Issue by Inscrutable** [md-5/Deadbolt#3]
Greetings. Just tried new build of Lockette, all works well. But doors/trapdoors still open-and-close at the end of the timer if they are closed by the player. Standing on a trapdoor allows bypass if this occurs, but impact is otherwise minor. Preferably, Timer check should recognise closed state and keep closed. Me not know java much. You help fix, me be happy :D
(I hope this is the right place, theres no Ticket link on the BukkitDev page) RB1060 MC1.73 PEx1.13 yadda yadda

**Comment by daemitus** [comment]
Fixed in 1.1
