### ISSUE TITLE
Unable to make signs for other players.

### ISSUE THREAD

**Issue by godsyn** [md-5/Deadbolt#30]
You can no longer protect items for other players (all permissions/ops). Creating a sign with [private] as the header and the player's name as the 2nd line no longer works (it overrides with the creator's name).

**Comment by md-5** [comment]
Ill check

**Comment by md-5** [comment]
Closed, I cannot reproduce this.

**Comment by daemitus** [comment]
I had this issue about a week ago. I may have stealth fixed it. So stealthy I hid it from myself.

**Comment by godsyn** [comment]
http://imgur.com/ZZ4BM
In game example.

**Comment by daemitus** [comment]
Tried to reproduce with 2.0.8, couldnt reproduce. Are you sure you have deadbolt.admin.create or OP?

**Comment by daemitus** [comment]
Of note, tried to reproduce on the live server, which is like 3-5 versions behind and it did work. Updated, and it was fixed.

**Comment by godsyn** [comment]
Update: only occurs if the player on line 2 is online. Just tested with 2.0.8.
Sorry for the lack of the deciding factor.. Sometimes it would work, sometimes it wouldn't. 
I attempted to make another sign (no restarts/reloads) as in the image above, and it worked.
At this point I'm thinking I'm crazy.
Then it hit me.
TP'd to a player online, and I couldn't make a chest for them.

CB: 1619
DB: 2.0.8

**Comment by daemitus** [comment]
Now thats an interesting one. Ill take a look.

**Comment by daemitus** [comment]
https://github.com/daemitus/Deadbolt/blob/master/release/2.0.9%201.0.1-R2/Deadbolt.jar?raw=true

That should take care of that. Also, the lock your chest notification wasnt firing, and Towny Listener has plot level permissions worked into it.
