### ISSUE TITLE
Reloading breaks private sign placement

### ISSUE THREAD

**Issue by Chromana** [md-5/Deadbolt#32]
Deadbolt 2.0.7,  CB1597
After "/deadbolt reload" I tried to protect a chest just by writing [private]. Outcome:
http://img.ctrlv.in/4ef9363675500.jpg
This also happens if I manually write my name on the 2nd line except the 2nd line says "0Chromana".

Placing directly on a chest (quick-place):
http://img.ctrlv.in/4ef9369f57116.jpg

Breaking the second sign gives the wrong name for the admin break notice:
http://img.ctrlv.in/4ef936d8957dc.jpg
(Surely it would have said "0Chromana"?)

Colours should be the following, so not sure why it is putting 0 on the lines anyway:
default_colors_private_line_1: c  
default_colors_private_line_2: 2  
default_colors_private_line_3: 2  
default_colors_private_line_4: 2 

Same issue with doors. Haven't tested on other blocks.
Server restart fixes everything.

**Comment by daemitus** [comment]
Thought I fixed that too. apparently not. Lemme look into it.

**Comment by daemitus** [comment]
Ok, its specific to the reload then. I can fix that quickly enough probably.

**Comment by daemitus** [comment]
Ok, fixed this one. Also, make sure you quote the color, otherwise it will try to think its a number, and drop the c. Basically, default_colors_private_line_1: "c"

**Comment by daemitus** [comment]
http://dev.bukkit.org/server-mods/deadbolt/files/44-2-0-8/

**Comment by Chromana** [comment]
Seems to work now.
