### ISSUE TITLE
Numeric default colour codes don't work

### ISSUE THREAD

**Issue by Chromana** [md-5/Deadbolt#33]
default_colors_private_line_1: c  
default_colors_private_line_2: d  
default_colors_private_line_3: 6  
default_colors_private_line_4: 5   

Will produce
http://img.ctrlv.in/4ef93aaec564e.jpg
Adding & in front of any numeric codes will make all the text black.

**Comment by Chromana** [comment]
Manually writing the codes on the signs works though.

**Comment by daemitus** [comment]
Fixed, uploading now. As with the other error, make sure you quote your color codes. 

default_colors_private_line_1: "c" 

Ive changed the default config to reflect this. The & is automatically applied in the code, you just need the color code.

**Comment by daemitus** [comment]
http://dev.bukkit.org/server-mods/deadbolt/files/44-2-0-8/
