### ISSUE TITLE
Permissions read prior to reminder fire.

### ISSUE THREAD

**Issue by godsyn** [md-5/Deadbolt#34]
Please check if users can protect something prior to displaying a message reminder to protect it.
EG: 
- Player without deadbolt.user.create.door places a door.
- Message "msg_reminder_lock_your_chests:          "Place a sign headed [Private] next to your chest to lock it" fires.
- Confusion ensues.

CB: 1619
DB: 2.0.8r2

**Comment by godsyn** [comment]
Disregard. User error.
This seems to only fire once per server start.. if it happens at all.

**Comment by daemitus** [comment]
https://github.com/daemitus/Deadbolt/blob/master/release/2.0.10%201.0.1-R2/Deadbolt.jar?raw=true

**Comment by godsyn** [comment]
Fixed before I could even re-comment. Thanks for the fixes tonight!
