### ISSUE TITLE
Protection for groups using [Groupname]

### ISSUE THREAD

**Issue by Chromana** [md-5/Deadbolt#36]
Hi, I came from Lockette so have a bunch of signs on my server which allow certain groups to use the chests. E.g.
[Private]
Chromana
[Trusted]

So anyone from the Trusted group could use the chest.
Deadbolt doesn't seem to have this functionality, or it's broken. Can you help me out?

**Comment by daemitus** [comment]
Depends on the permissions system you use. Open up the JAR in whatever zip program you use, and grab xxxListener.class, put it in Deadbolt/listeners.

For example, PermissionsExListener.class if you use PermissionsEx to make permissions groups.

**Comment by Chromana** [comment]
Hmm well I did as you said and it's not working. I am indeed using PEX so I stuck PermissionsExListener.class into the Deadbolt/listeners folder in the jar. Or so you mean to put it in the Deadbolt/listeners plugin folder on the server?

**Comment by daemitus** [comment]
On the server, sorry for the confusion. /plugins/Deadbolt/listeners
