### ISSUE TITLE
[feature request] Don't eat action if permission not found.

### ISSUE THREAD

**Issue by godsyn** [md-5/Deadbolt#39]
When attempting to open a door/trapdoor/whatever with a sign in hand, and the player has no permission to protect said item, and the player has a sign in hand, the msg_deny_block_perm fires and it eats the event (opening the door).

If the player has permission to open the door (eg: it isn't already protected) with the above situation, could we not eat the event, please?

Also, is it possible to remove the warning msg_deny_block_perm? Meaning they get no message. Is it as simple as making:

```
msg_deny_block_perm: "" 
```

(meaning display no message)
I'd prefer my users to not know that the function to protect whatever I choose not to provide permissions for even exists.

**Comment by md-5** [comment]
Will do

**Comment by godsyn** [comment]
Awesome! Thank you!

**Comment by md-5** [comment]
msg_deny_block_perm: "" 

Cant do that, bukkit limitation

**Comment by godsyn** [comment]
if var !null, then can't be done? That bites. :( thanks the same.

Perhaps a permission (default on) to receive above message?

**Comment by md-5** [comment]
Ill check how we are copying variables.

**Comment by md-5** [comment]
Fixed
