### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by NolanSyKinsley** [md-5/Deadbolt#46]
I am trying to compile this plugin to make a server specific fix, but all I get is this error:

[ERROR] Failed to execute goal on project Deadbolt: Could not resolve dependencies for project com.daemitus:Deadbolt:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.bukkit:bukkit:jar:1.1-R2, de.bananaco:bPermissions:jar:1337-SNAPSHOT, com.palmergames.bukkit:Towny:jar:1.0, net.sacredlabyrinth.phaed:SimpleClans:jar:1.0, org.anjocaido:GroupManager:jar:1.0, com.platymuus.bukkit:BukkitPermissions:jar:1.2, ru.tehkode:PermissionsEx:jar:1.18, net.milkbowl.vault:Vault:jar:0.0.1-SNAPSHOT: Could not find artifact org.bukkit:bukkit:jar:1.1-R2 in guardian-repo (http://guardian.mossycobble.com:8080/repo/content/groups/public/)

**Comment by daemitus** [comment]
The problem is all the stuff in the root folder. delete all of the listeners and it should compile then. Or you can grab vault, bperms, PEX, etc. and add them as libraries.

**Comment by NolanSyKinsley** [comment]
actually the repo address is wrong, it should be http://guardian.mossycobble.com:8080/nexus/content/groups/public/

the repo is missing vault and the version numbers need to be corrected for the dependencies, I tried deleting all of the listeners in the root, did not work. I have no clue how to add them as libraries, I have only been at this a few weeks....
