### ISSUE TITLE
Bridges are missing dependancies

### ISSUE THREAD

**Issue by nvx** [md-5/Deadbolt#5]
The Lockette bridges do not have dependency information in the plugin.yml files requiring Lockette and whichever plugin they bridge with.

See http://forums.bukkit.org/threads/9923/ for more information on how to add dependency information to the plugins. I assume the plugins being prefixed with 'zzz' is to ensure they are loaded last (ie, before any dependencies), but on case some sensitive platforms, lowercase letters are sorted before uppercase, so zzz<name> is loaded before Lockette.

Using bukkit's dependency capabilities in plugin.yml solves this, and allows for the plugin name to be cleaner.

**Comment by daemitus** [comment]
This. Is. Awesome.

**Comment by md-5** [comment]
Daemitus are you fixing it now or should I?

**Comment by md-5** [comment]
Actually just reading up on dependencies now it seems this wouln't work as it would make ALL bridges REQUIRED before the plugin is loaded.

**Comment by daemitus** [comment]
No, the idea would make the bridge not load unless, for example towny is not loaded. Not require all bridges for lockette.

**Comment by nvx** [comment]
Yeah, in: Lockette / bridges / PermissionsBukkit / src / plugin.yml 

You would need at the bottom of the file:

depend:
    - Lockette
    - PermissionsBukkit

Repeat for all other Bridges replacing PermissionsBukkit with the name of the plugin (as per its plugin.yml). Just tested it out by editing the PermissionsBukkit bridge jar file to add those 3 lines at the end and it works beautifully (including fixing the big stacktrace I was getting before I made the changes as the bridge loaded before Lockette had a change to load - so a java.lang.NoClassDefFoundError was thrown for com/daemitus/lockette/bridge/LocketteBridge).

**Comment by nvx** [comment]
Goddamn that comment and close button.

**Comment by md-5** [comment]
I hate it too Daemitus is doing that now. In the mean while do you have any bright ideas for a new name?

**Comment by daemitus** [comment]
Fixed. Except for simpleclans :\
