### ISSUE TITLE
Please update for R6 (MC 1.2.2)

### ISSUE THREAD

**Issue by asweiler** [md-5/Deadbolt#53]
http://dl.bukkit.org/downloads/craftbukkit/

**Comment by krosk93** [comment]
As far as I know there's no R6 for MC1.2.2, there's R6 for MC1.1, R0.1 for MC1.2.2 and R0.1 and R0.2 for MC1.2.3.

**Comment by asweiler** [comment]
It was called R6 for 1.2.2 before they made 1.1 R6 my bad.

Now it is as you mentioned and I tried the new version uploaded. It works great thank you.
