### ISSUE TITLE
Rework messages in onsignupdate/line change command help

### ISSUE THREAD

**Issue by daemitus** [md-5/Deadbolt#8]
Needs clarification on exactly what is possible due to color feature prior to 1.2 release

/deadbolt line text

[Private]:
line1, color only
line2, color only
line3/4, anything

[More Users]
line1, color only
line3/4/5, anything

**Comment by md-5** [comment]
Elaborate

**Comment by daemitus** [comment]
For example, trying to change line1 gives an error. it should include that you CAN change color though. but it does not currently.

**Comment by md-5** [comment]
You gonna fix or shall I?

**Comment by daemitus** [comment]
If youve got free time, take a look. Otherwise itll probably sit until monday

**Comment by md-5** [comment]
O.K

**Comment by md-5** [comment]
O.K line 1 is fixed, working on line 2, seems different.
i can also change line 2 owner - bad

**Comment by md-5** [comment]
Fixed
