### ISSUE TITLE
minecart with a hopper bypass deadbolts

### ISSUE THREAD

**Issue by AbooseYou** [md-5/Deadbolt#88]
Hi I am a mod from MassiveCraft
You can steal from deadbolted chests with a minecart with a hopper.
We are using build 15

<img src="http://i.imgur.com/9j9T1xv.png">
<img src="http://i.imgur.com/9POKxI9.png">
<img src="http://i.imgur.com/OjzLoDL.png">
<img src="http://i.imgur.com/wZtPxQS.png">

**Comment by CoolV1994** [comment]
This is an issue for every server running build 15. Unless there is another form of protection to protect around the chest, those items are as good as gone.

**Comment by socram8888** [comment]
Fixed in PR #97
